version: '2.1'

services:
  notebook:
    image: felix/jupyter-opencv-notebook
    build: .
    ports:
      - 8888:8888
    environment:
      NB_UID: ${NB_UID:-1000}
    # https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook#docker-options
    # root will drop privileges
    user: root
    volumes:
      - ./notebooks:/home/jovyan/work
